//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Chat9xType.proto
// Note: requires additional types generated from: CommonData.proto
// Note: requires additional types generated from: MessageData.proto
// Note: requires additional types generated from: ServerData.proto
namespace DataContract
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_PrepareDataForEnterGame_RET_int32__")]
  public partial class __RPC_Chat_PrepareDataForEnterGame_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_PrepareDataForEnterGame_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_PrepareDataForEnterGame_ARG_int32_serverId__")]
  public partial class __RPC_Chat_PrepareDataForEnterGame_ARG_int32_serverId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_PrepareDataForEnterGame_ARG_int32_serverId__() {}
    

    private int _ServerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_PrepareDataForCreateCharacter_RET_int32__")]
  public partial class __RPC_Chat_PrepareDataForCreateCharacter_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_PrepareDataForCreateCharacter_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_PrepareDataForCreateCharacter_ARG_int32_type__")]
  public partial class __RPC_Chat_PrepareDataForCreateCharacter_ARG_int32_type__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_PrepareDataForCreateCharacter_ARG_int32_type__() {}
    

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_PrepareDataForCommonUse_RET_int32__")]
  public partial class __RPC_Chat_PrepareDataForCommonUse_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_PrepareDataForCommonUse_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_PrepareDataForCommonUse_ARG_uint32_placeholder__")]
  public partial class __RPC_Chat_PrepareDataForCommonUse_ARG_uint32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_PrepareDataForCommonUse_ARG_uint32_placeholder__() {}
    

    private uint _Placeholder = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_PrepareDataForLogout_RET_int32__")]
  public partial class __RPC_Chat_PrepareDataForLogout_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_PrepareDataForLogout_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_PrepareDataForLogout_ARG_uint32_placeholder__")]
  public partial class __RPC_Chat_PrepareDataForLogout_ARG_uint32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_PrepareDataForLogout_ARG_uint32_placeholder__() {}
    

    private uint _Placeholder = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_CreateCharacter_RET_int32__")]
  public partial class __RPC_Chat_CreateCharacter_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_CreateCharacter_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_CreateCharacter_ARG_int32_type__")]
  public partial class __RPC_Chat_CreateCharacter_ARG_int32_type__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_CreateCharacter_ARG_int32_type__() {}
    

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_DelectCharacter_RET_int32__")]
  public partial class __RPC_Chat_DelectCharacter_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_DelectCharacter_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_DelectCharacter_ARG_int32_type__")]
  public partial class __RPC_Chat_DelectCharacter_ARG_int32_type__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_DelectCharacter_ARG_int32_type__() {}
    

    private int _Type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SBGetAllOnlineCharacterInServer_RET_Uint64Array__")]
  public partial class __RPC_Chat_SBGetAllOnlineCharacterInServer_RET_Uint64Array__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SBGetAllOnlineCharacterInServer_RET_Uint64Array__() {}
    

    private DataContract.Uint64Array _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.Uint64Array ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SBGetAllOnlineCharacterInServer_ARG_int32_serverId__")]
  public partial class __RPC_Chat_SBGetAllOnlineCharacterInServer_ARG_int32_serverId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SBGetAllOnlineCharacterInServer_ARG_int32_serverId__() {}
    

    private int _ServerId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_CheckConnected_RET_int32__")]
  public partial class __RPC_Chat_CheckConnected_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_CheckConnected_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_CheckConnected_ARG_uint64_characterId__")]
  public partial class __RPC_Chat_CheckConnected_ARG_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_CheckConnected_ARG_uint64_characterId__() {}
    

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_CheckLost_RET_int32__")]
  public partial class __RPC_Chat_CheckLost_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_CheckLost_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_CheckLost_ARG_uint64_characterId__")]
  public partial class __RPC_Chat_CheckLost_ARG_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_CheckLost_ARG_uint64_characterId__() {}
    

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_QueryStatus_RET_ChatServerStatus__")]
  public partial class __RPC_Chat_QueryStatus_RET_ChatServerStatus__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_QueryStatus_RET_ChatServerStatus__() {}
    

    private DataContract.ChatServerStatus _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatServerStatus ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_QueryStatus_ARG_uint32_placeholder__")]
  public partial class __RPC_Chat_QueryStatus_ARG_uint32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_QueryStatus_ARG_uint32_placeholder__() {}
    

    private uint _Placeholder = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_QueryBrokerStatus_RET_CommonBrokerStatus__")]
  public partial class __RPC_Chat_QueryBrokerStatus_RET_CommonBrokerStatus__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_QueryBrokerStatus_RET_CommonBrokerStatus__() {}
    

    private DataContract.CommonBrokerStatus _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.CommonBrokerStatus ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_QueryBrokerStatus_ARG_uint32_placeholder__")]
  public partial class __RPC_Chat_QueryBrokerStatus_ARG_uint32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_QueryBrokerStatus_ARG_uint32_placeholder__() {}
    

    private uint _Placeholder = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GMChat_RET_int32__")]
  public partial class __RPC_Chat_GMChat_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GMChat_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GMChat_ARG_string_commond__")]
  public partial class __RPC_Chat_GMChat_ARG_string_commond__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GMChat_ARG_string_commond__() {}
    

    private string _Commond = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Commond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Commond
    {
      get { return _Commond; }
      set { _Commond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_ChatChatMessage_RET_int32__")]
  public partial class __RPC_Chat_ChatChatMessage_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_ChatChatMessage_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_ChatChatMessage_ARG_int32_chatType_ChatMessageContent_Content_uint64_characterId__")]
  public partial class __RPC_Chat_ChatChatMessage_ARG_int32_chatType_ChatMessageContent_Content_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_ChatChatMessage_ARG_int32_chatType_ChatMessageContent_Content_uint64_characterId__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_ChatNotify_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__")]
  public partial class __RPC_Chat_ChatNotify_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_ChatNotify_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private string _CharacterName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharacterName
    {
      get { return _CharacterName; }
      set { _CharacterName = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SendHornMessage_RET_int32__")]
  public partial class __RPC_Chat_SendHornMessage_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SendHornMessage_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SendHornMessage_ARG_uint32_serverId_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__")]
  public partial class __RPC_Chat_SendHornMessage_ARG_uint32_serverId_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SendHornMessage_ARG_uint32_serverId_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__() {}
    

    private uint _ServerId = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private string _CharacterName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"CharacterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharacterName
    {
      get { return _CharacterName; }
      set { _CharacterName = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SyncChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__")]
  public partial class __RPC_Chat_SyncChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SyncChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private string _CharacterName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharacterName
    {
      get { return _CharacterName; }
      set { _CharacterName = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_BroadcastWorldMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__")]
  public partial class __RPC_Chat_BroadcastWorldMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_BroadcastWorldMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private string _CharacterName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharacterName
    {
      get { return _CharacterName; }
      set { _CharacterName = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_ServerGMCommand_ARG_string_cmd_string_param__")]
  public partial class __RPC_Chat_ServerGMCommand_ARG_string_cmd_string_param__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_ServerGMCommand_ARG_string_cmd_string_param__() {}
    

    private string _Cmd = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Cmd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Cmd
    {
      get { return _Cmd; }
      set { _Cmd = value; }
    }

    private string _Param = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Param", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Param
    {
      get { return _Param; }
      set { _Param = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_ReadyToEnter_RET_int32__")]
  public partial class __RPC_Chat_ReadyToEnter_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_ReadyToEnter_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_ReadyToEnter_ARG_int32_placeholder__")]
  public partial class __RPC_Chat_ReadyToEnter_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_ReadyToEnter_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_UpdateServer_ARG_int32_placeholder__")]
  public partial class __RPC_Chat_UpdateServer_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_UpdateServer_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GetRecentcontacts_RET_PlayerHeadInfoMsgList__")]
  public partial class __RPC_Chat_GetRecentcontacts_RET_PlayerHeadInfoMsgList__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GetRecentcontacts_RET_PlayerHeadInfoMsgList__() {}
    

    private DataContract.PlayerHeadInfoMsgList _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.PlayerHeadInfoMsgList ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GetRecentcontacts_ARG_int32_placeholder__")]
  public partial class __RPC_Chat_GetRecentcontacts_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GetRecentcontacts_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_DeleteRecentcontacts_RET_int32__")]
  public partial class __RPC_Chat_DeleteRecentcontacts_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_DeleteRecentcontacts_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_DeleteRecentcontacts_ARG_uint64_characterId__")]
  public partial class __RPC_Chat_DeleteRecentcontacts_ARG_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_DeleteRecentcontacts_ARG_uint64_characterId__() {}
    

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_AddRecentcontacts_ARG_LogicSimpleData_simpleData__")]
  public partial class __RPC_Chat_AddRecentcontacts_ARG_LogicSimpleData_simpleData__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_AddRecentcontacts_ARG_LogicSimpleData_simpleData__() {}
    

    private DataContract.LogicSimpleData _SimpleData = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SimpleData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.LogicSimpleData SimpleData
    {
      get { return _SimpleData; }
      set { _SimpleData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_EnterChannel_RET_int32__")]
  public partial class __RPC_Chat_EnterChannel_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_EnterChannel_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_EnterChannel_ARG_uint64_channelId_string_password__")]
  public partial class __RPC_Chat_EnterChannel_ARG_uint64_channelId_string_password__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_EnterChannel_ARG_uint64_channelId_string_password__() {}
    

    private ulong _ChannelId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChannelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ChannelId
    {
      get { return _ChannelId; }
      set { _ChannelId = value; }
    }

    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_LeaveChannel_RET_int32__")]
  public partial class __RPC_Chat_LeaveChannel_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_LeaveChannel_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_LeaveChannel_ARG_uint64_channelId__")]
  public partial class __RPC_Chat_LeaveChannel_ARG_uint64_channelId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_LeaveChannel_ARG_uint64_channelId__() {}
    

    private ulong _ChannelId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChannelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ChannelId
    {
      get { return _ChannelId; }
      set { _ChannelId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SyncToListCityChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_Content_string_ChannelName__")]
  public partial class __RPC_Chat_SyncToListCityChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_Content_string_ChannelName__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SyncToListCityChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_Content_string_ChannelName__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private string _CharacterName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharacterName
    {
      get { return _CharacterName; }
      set { _CharacterName = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }

    private string _ChannelName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ChannelName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ChannelName
    {
      get { return _ChannelName; }
      set { _ChannelName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_CacheChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__")]
  public partial class __RPC_Chat_CacheChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_CacheChatMessage_ARG_int32_chatType_uint64_characterId_string_characterName_ChatMessageContent_content__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private string _CharacterName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CharacterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharacterName
    {
      get { return _CharacterName; }
      set { _CharacterName = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SBCleanClientCharacterData_ARG_uint64_clientId_uint64_characterId__")]
  public partial class __RPC_Chat_SBCleanClientCharacterData_ARG_uint64_clientId_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SBCleanClientCharacterData_ARG_uint64_clientId_uint64_characterId__() {}
    

    private ulong _ClientId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ClientId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ClientId
    {
      get { return _ClientId; }
      set { _ClientId = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SSNotifyCharacterOnConnet_RET_int32__")]
  public partial class __RPC_Chat_SSNotifyCharacterOnConnet_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SSNotifyCharacterOnConnet_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SSNotifyCharacterOnConnet_ARG_uint64_clientId_uint64_characterId__")]
  public partial class __RPC_Chat_SSNotifyCharacterOnConnet_ARG_uint64_clientId_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SSNotifyCharacterOnConnet_ARG_uint64_clientId_uint64_characterId__() {}
    

    private ulong _ClientId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ClientId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ClientId
    {
      get { return _ClientId; }
      set { _ClientId = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_BSNotifyCharacterOnLost_ARG_uint64_clientId_uint64_characterId__")]
  public partial class __RPC_Chat_BSNotifyCharacterOnLost_ARG_uint64_clientId_uint64_characterId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_BSNotifyCharacterOnLost_ARG_uint64_clientId_uint64_characterId__() {}
    

    private ulong _ClientId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ClientId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ClientId
    {
      get { return _ClientId; }
      set { _ClientId = value; }
    }

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_Silence_RET_int32__")]
  public partial class __RPC_Chat_Silence_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_Silence_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_Silence_ARG_uint32_mask__")]
  public partial class __RPC_Chat_Silence_ARG_uint32_mask__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_Silence_ARG_uint32_mask__() {}
    

    private uint _Mask = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Mask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Mask
    {
      get { return _Mask; }
      set { _Mask = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GetSilenceState_RET_uint32__")]
  public partial class __RPC_Chat_GetSilenceState_RET_uint32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GetSilenceState_RET_uint32__() {}
    

    private uint _ReturnValue = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GetSilenceState_ARG_int32_placeholder__")]
  public partial class __RPC_Chat_GetSilenceState_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GetSilenceState_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_ApplyAnchorRoomInfo_RET_MsgAnchorInfo__")]
  public partial class __RPC_Chat_ApplyAnchorRoomInfo_RET_MsgAnchorInfo__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_ApplyAnchorRoomInfo_RET_MsgAnchorInfo__() {}
    

    private DataContract.MsgAnchorInfo _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.MsgAnchorInfo ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_ApplyAnchorRoomInfo_ARG_int32_placeholder__")]
  public partial class __RPC_Chat_ApplyAnchorRoomInfo_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_ApplyAnchorRoomInfo_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SSBroadcastAllServerMsg_RET_int32__")]
  public partial class __RPC_Chat_SSBroadcastAllServerMsg_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SSBroadcastAllServerMsg_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SSBroadcastAllServerMsg_ARG_int32_chatType_string_charName_ChatMessageContent_content__")]
  public partial class __RPC_Chat_SSBroadcastAllServerMsg_ARG_int32_chatType_string_charName_ChatMessageContent_content__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SSBroadcastAllServerMsg_ARG_int32_chatType_string_charName_ChatMessageContent_content__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }

    private string _CharName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CharName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharName
    {
      get { return _CharName; }
      set { _CharName = value; }
    }

    private DataContract.ChatMessageContent _Content = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.ChatMessageContent Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SSGetCurrentAnchor_RET_uint64__")]
  public partial class __RPC_Chat_SSGetCurrentAnchor_RET_uint64__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SSGetCurrentAnchor_RET_uint64__() {}
    

    private ulong _ReturnValue = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_SSGetCurrentAnchor_ARG_int32_placeholder__")]
  public partial class __RPC_Chat_SSGetCurrentAnchor_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_SSGetCurrentAnchor_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_PresentGift_RET_int32__")]
  public partial class __RPC_Chat_PresentGift_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_PresentGift_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_PresentGift_ARG_int32_itemId_int32_count__")]
  public partial class __RPC_Chat_PresentGift_ARG_int32_itemId_int32_count__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_PresentGift_ARG_int32_itemId_int32_count__() {}
    

    private int _ItemId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ItemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ItemId
    {
      get { return _ItemId; }
      set { _ItemId = value; }
    }

    private int _Count = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Count
    {
      get { return _Count; }
      set { _Count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_BroadcastAnchorOnline_ARG_string_charName_int32_online__")]
  public partial class __RPC_Chat_BroadcastAnchorOnline_ARG_string_charName_int32_online__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_BroadcastAnchorOnline_ARG_string_charName_int32_online__() {}
    

    private string _CharName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharName
    {
      get { return _CharName; }
      set { _CharName = value; }
    }

    private int _Online = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Online
    {
      get { return _Online; }
      set { _Online = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_NotifyChatRoseEffectChange_ARG_int32_chatType__")]
  public partial class __RPC_Chat_NotifyChatRoseEffectChange_ARG_int32_chatType__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_NotifyChatRoseEffectChange_ARG_int32_chatType__() {}
    

    private int _ChatType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_NotifyAnchorEnterRoomChange_RET_int32__")]
  public partial class __RPC_Chat_NotifyAnchorEnterRoomChange_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_NotifyAnchorEnterRoomChange_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_NotifyAnchorEnterRoomChange_ARG_int32_chat__")]
  public partial class __RPC_Chat_NotifyAnchorEnterRoomChange_ARG_int32_chat__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_NotifyAnchorEnterRoomChange_ARG_int32_chat__() {}
    

    private int _Chat = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Chat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Chat
    {
      get { return _Chat; }
      set { _Chat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_BroadcastAnchorEnterRoom_ARG_string_charName__")]
  public partial class __RPC_Chat_BroadcastAnchorEnterRoom_ARG_string_charName__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_BroadcastAnchorEnterRoom_ARG_string_charName__() {}
    

    private string _CharName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string CharName
    {
      get { return _CharName; }
      set { _CharName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_AnchorExitRoom_ARG_int32_chat__")]
  public partial class __RPC_Chat_AnchorExitRoom_ARG_int32_chat__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_AnchorExitRoom_ARG_int32_chat__() {}
    

    private int _Chat = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Chat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Chat
    {
      get { return _Chat; }
      set { _Chat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GMCommand_RET_Int32Array__")]
  public partial class __RPC_Chat_GMCommand_RET_Int32Array__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GMCommand_RET_Int32Array__() {}
    

    private DataContract.Int32Array _ReturnValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.Int32Array ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GMCommand_ARG_StringArray_commonds__")]
  public partial class __RPC_Chat_GMCommand_ARG_StringArray_commonds__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GMCommand_ARG_StringArray_commonds__() {}
    

    private DataContract.StringArray _Commonds = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Commonds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.StringArray Commonds
    {
      get { return _Commonds; }
      set { _Commonds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_CloneCharacterDbById_RET_int32__")]
  public partial class __RPC_Chat_CloneCharacterDbById_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_CloneCharacterDbById_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_CloneCharacterDbById_ARG_uint64_fromId_uint64_toId__")]
  public partial class __RPC_Chat_CloneCharacterDbById_ARG_uint64_fromId_uint64_toId__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_CloneCharacterDbById_ARG_uint64_fromId_uint64_toId__() {}
    

    private ulong _FromId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"FromId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong FromId
    {
      get { return _FromId; }
      set { _FromId = value; }
    }

    private ulong _ToId = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ToId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ToId
    {
      get { return _ToId; }
      set { _ToId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_NotifyPlayerEnterGame_ARG_MsgChatMoniterData_data__")]
  public partial class __RPC_Chat_NotifyPlayerEnterGame_ARG_MsgChatMoniterData_data__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_NotifyPlayerEnterGame_ARG_MsgChatMoniterData_data__() {}
    

    private DataContract.MsgChatMoniterData _Data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DataContract.MsgChatMoniterData Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_AddPlayerToChatMonitor_ARG_int32_placeholder__")]
  public partial class __RPC_Chat_AddPlayerToChatMonitor_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_AddPlayerToChatMonitor_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GetAnchorIsInRoom_RET_int32__")]
  public partial class __RPC_Chat_GetAnchorIsInRoom_RET_int32__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GetAnchorIsInRoom_RET_int32__() {}
    

    private int _ReturnValue = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ReturnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ReturnValue
    {
      get { return _ReturnValue; }
      set { _ReturnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_GetAnchorIsInRoom_ARG_int32_placeholder__")]
  public partial class __RPC_Chat_GetAnchorIsInRoom_ARG_int32_placeholder__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_GetAnchorIsInRoom_ARG_int32_placeholder__() {}
    

    private int _Placeholder = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Placeholder", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Placeholder
    {
      get { return _Placeholder; }
      set { _Placeholder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"__RPC_Chat_NodifyModifyPlayerName_ARG_uint64_characterId_string_modifyName__")]
  public partial class __RPC_Chat_NodifyModifyPlayerName_ARG_uint64_characterId_string_modifyName__ : global::ProtoBuf.IExtensible
  {
    public __RPC_Chat_NodifyModifyPlayerName_ARG_uint64_characterId_string_modifyName__() {}
    

    private ulong _CharacterId = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CharacterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong CharacterId
    {
      get { return _CharacterId; }
      set { _CharacterId = value; }
    }

    private string _ModifyName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ModifyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ModifyName
    {
      get { return _ModifyName; }
      set { _ModifyName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}